DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS department;

CREATE TABLE department(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE role(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(45) NOT NULL,
salary DECIMAL(10.3) NOT NULL,
department_id INT NOT NULL,
CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES department(id)
);

CREATE TABLE employee(
id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(45) NOT NULL,
last_name VARCHAR(45) NOT NULL,
role_id INT NOT NULL,
manager_id INT REFERENCES employee(id),
CONSTRAINT fk_role_id FOREIGN KEY (role_id) REFERENCES role(id)
);